export interface IJob {
        JobId: string 
        EverJob: number,       
        LeaderCenters: string, 
        LtfOrPl: string, 
        ManagerSp: string, 
        Community: string,
        Squad: string, 
        ProjectId: string, 
        AllocationType: string, 
        OpeningDate: Date,
        Technology: string, 
        YearsOfExperience: number, 
        DesiredDate:Date, 
        MaximumSalary: number, 
        Recruiter: string, 
        Priority: number, 
        PriorityDate: Date, 
        Status: string, 
        Justification: string,
}
